
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 04 17:44:00 BRT 2025
//----------------------------------------------------

package Exercicio3;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MAIS = 3;
  public static final int MULT = 4;
  public static final int PTV = 2;
  public static final int error = 1;
  public static final int DIV = 5;
  public static final int EOF = 0;
  public static final int INTEIRO = 6;
}

