
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 08 20:14:09 BRT 2025
//----------------------------------------------------

package Exercicio2;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FECHA_PAREN = 14;
  public static final int MAIOR = 16;
  public static final int INTEIRO = 8;
  public static final int PROGRAMA = 2;
  public static final int INICIO = 3;
  public static final int PTV = 12;
  public static final int EOF = 0;
  public static final int TIPO_INT = 5;
  public static final int FIM = 4;
  public static final int ABRE_PAREN = 13;
  public static final int MULTIPLICA = 15;
  public static final int IF = 11;
  public static final int ATRIBUI = 7;
  public static final int TIPO_FLOAT = 6;
  public static final int error = 1;
  public static final int VARIAVEL = 10;
  public static final int FLOAT = 9;
}

